package info.moevm.se.nosqlcatsmemecached.utils.memcached.importers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class JsonCatsImporterImplTest {

    private final CatsImporter importer = new JsonCatsImporterImpl();


    @Test
    void fromString() {
        importer.from("[\n" +
                "  {\n" +
                "    \"breed_name\": \"Abyssinian\",\n" +
                "    \"care\": \"The short, fine coat of the Abyssinian is easily cared for with weekly combing to remove dead hair and distribute skin oils. A bath when the cat is shedding will help to remove excess hair more quickly.\\n\\nBrush the teeth to prevent periodontal disease. Daily dental hygiene is best, but weekly brushing is better than nothing. Trim the nails every couple of weeks. Wipe the corners of the eyes with a soft, damp cloth to remove any discharge. Use a separate area of the cloth for each eye so you don\\u2019t run the risk of spreading any infection. Check the ears weekly. If they look dirty, wipe them out with a cotton ball or soft damp cloth moistened with a 50-50 mixture of cider vinegar and warm water. Avoid using cotton swabs, which can damage the interior of the ear.\\n\\nKeep the litter box spotlessly clean. Cats are very particular about bathroom hygiene, and a dirty box may cause them to start using other places in the house instead.\\n\\nIt\\u2019s a good idea to keep an Abyssinian as an indoor-only cat to protect him from diseases spread by other cats, attacks by dogs or coyotes, and the other dangers that face cats who go outdoors, such as being hit by a car. Abyssinians who go outdoors also run the risk of being stolen by someone who would like to have such a beautiful cat without paying for it.\",\n" +
                "    \"characteristics\": {\n" +
                "      \"Affectionate with Family\": 3,\n" +
                "      \"Amount of Shedding\": 3,\n" +
                "      \"Easy to Groom\": 3,\n" +
                "      \"General Health\": 2,\n" +
                "      \"Intelligence\": 5,\n" +
                "      \"Kid-Friendly\": 5,\n" +
                "      \"Pet Friendly\": 5,\n" +
                "      \"Potential for Playfulness\": 5\n" +
                "    },\n" +
                "    \"children_and_pets\": \"The active and social Abyssinian is a perfect choice for families with children and cat-friendly dogs. He will play fetch as well as any retriever, learns tricks easily and loves the attention he receives from children who treat him politely and with respect. He\\u2019s smart enough to get out of the way of toddlers but loves school-age children because they are a match for his energy level and curiosity. Nothing scares him, certainly not dogs, and he will happily make friends with them if they don\\u2019t give him any trouble. Abys have also been known to get along with large parrots, ferrets and other animals. Always introduce any pets, even other cats, slowly and in a controlled setting.\",\n" +
                "    \"color_and_grooming\": \"The Aby is often said to look as if he had just walked straight out of the wild. That\\u2019s because of his ticked coat pattern, which resembles that of wild cats such as cougars. A ticked coat has alternating light and dark bands of color on each hair shaft.\\n\\nEverything about him suggests his lively, attentive nature. The Aby has a slightly rounded wedge-shaped head topped with large, broad ears, the better to hear you with. Large, almond-shaped eyes of gold or green express interest in everything they see. On the face, dark lines may extend from the eyes and brows.\\n\\nThe muscular body is graceful and athletic. It falls into a middle ground between the stocky, or cobby, body of a breed such as the Persian and the long, svelte body of the Oriental breeds such as the Siamese. The body is supported by slim, fine-boned legs atop small, oval, compact paws. Abys are often said to look as if they are walking on tip-toe. Swishing behind them is a long, tapering tail.\\n\\nIts bands of color give the Aby\\u2019s coat a warm, glowing appearance. To the touch, the medium-length hair is soft and silky with a fine texture.\\n\\nThe coat comes in four main colors: ruddy brown, more artistically described as burnt sienna and ticked with darker brown or black, with tile-red nose leather and black or brown paw pads; red (sometimes called sorrel), a cinnamon shade ticked with chocolate-brown, with pink nose leather and paw pads; blue, a warm beige ticked with various shades of slate blue, with nose leather described as old rose and paw pads as mauve; and fawn, a warm rose-beige ticked with light cocoa-brown, with salmon-colored nose leather and pink paw pads. Some associations permit additional colors, including chocolate, lilac, and various silver tones.\",\n" +
                "    \"health\": \"Both pedigreed cats and mixed-breed cats have varying incidences of health problems that may be genetic in nature. Problems that may affect the Abyssinian include the following:\\n\\n\\u00a0\\n\\nEarly-onset periodontal disease\\n\\nHyperesthesia syndrome, a neurological problem that can cause cats to excessively groom themselves, leading to hair loss, and to act frantically, especially when they are touched or petted\\n\\nPatellar luxation, a hereditary dislocation of the kneecap that can range from mild to severe. Severe cases can be alleviated with surgery.\\n\\nProgressive retinal atrophy, a degenerative eye disease.\\n\\nPyruvate kinase deficiency (PKD), for which a genetic test is available to identify carriers.\\n\\nRenal amyloidosis, a heritable disease that occurs when a type of protein called amyloid is deposited in body organs, primarily the kidneys in Abyssinians. It eventually leads to kidney failure.\",\n" +
                "    \"history\": \"Showing cats was all the rage in the late Victorian era. One of the unusual breeds exhibited at the Crystal Palace Cat Show in 1871 was an Abyssinian \\u2014 \\u201ccaptured in the late Abyssinian War\\u201d \\u2014 who took third place. The report on the cat show, published in the January 27, 1872, issue of Harper\\u2019s Weekly, was the first known mention in print of the breed. Unfortunately, no records exist regarding the cats\\u2019 origins, although myths and speculation abound, including claims that it was the cat of the pharaohs, and that it was created in Britain by crossing silver and brown tabbies with cats that had \\u201cticked\\u201d coats.\\n\\nToday, genetic evidence suggests that the cats came from Indian Ocean coastal regions and parts of Southeast Asia. British and Dutch traders may well have brought the cats from ports such as Calcutta, India, or the islands of Indonesia. A taxidermied specimen of a ruddy ticked cat exhibited in the 1830s at the Leiden Zoological Museum in The Netherlands, where he was labeled \\u201cPatrie, domestica India,\\u201d gives creedence to that theory. The cats were probably given the name Abyssinian because Zula, the cat exhibited at the Crystal Palace, was said to have been imported from Abyssinia (now Ethiopia). Early pedigrees show crosses to non-Abyssinian cats, which may explain the introduction of new coat colors and the gene for long hair.\\n\\nAmerican cat fanciers first imported some Abyssinians in 1900, but Abyssinian breeding programs didn\\u2019t get a real start in the United States until the 1930s, when more of the cats were imported from Britain. It\\u2019s a good thing that a number of cats were exported to the U.S. because World War II devastated the breed. Only a dozen of the cats had survived in England by the end of the war. The breed bounced back, however, and has become one of the most popular cat breeds.\",\n" +
                "    \"personality\": \"Of all the cat breeds, the Abyssinian is perhaps the one who lives life to the fullest. He climbs higher, jumps farther, plays harder. Nothing escapes the notice of this highly intelligent and inquisitive cat, a quality that makes life with him both endlessly entertaining and continuously challenging. Staying a step ahead of an Aby, as the breed is nicknamed, or even just keeping pace with him, requires the fancy footwork of a Fred Astaire, the brainpower of an Einstein and a sense of humor that never stops. You never know what he\\u2019ll get into next, although you can assume that if you have something or are doing something, your Aby will want to investigate it closely. Some people refer to the cats as \\u201cAby-grabbys\\u201d because of their propensity for taking things that catch their interest.\\n\\nSometimes it may seem as if the Aby never sleeps. He is ever in motion, jumping up in the window to look at birds or squirrels, leaping on top of the refrigerator to supervise meal preparation, perching on your desk to watch your fingers move over the keyboard and then swiping at them so you\\u2019ll pay attention to him instead. This is a playful, persistent cat who adores being the center of attention and will do anything to achieve and maintain that status.\\n\\nThe Aby loves to play, so plan on making or purchasing a variety of toys to keep him occupied. Ping-Pong balls, bottle caps, wadded-up pieces of paper, puzzle toys and teasers such as big peacock feathers will all amuse this busy and brainy cat. Teach him to retrieve at your peril. Once you start, he won\\u2019t let you stop. He learns tricks quickly and many Abys enjoy running a feline agility course.\\n\\nA love of heights is a signal trait of the Abyssinian. He likes to be as high up as possible and will appreciate having one or more ceiling-height cat trees. When those aren\\u2019t available, he is perfectly capable of making his way to the uppermost point of any room. Fortunately, he is naturally graceful and rarely breaks items unless it is simply out of curiosity.\\n\\nAbys are adaptable throughout their lives and fit well into any home where they are loved and given plenty of attention. In a home where people are at work or school during the day, the Aby does best with a companion, ideally another Aby, who can match his activity level. If left to his own devices, the Aby may well dismantle the house in his search for something interesting to do.\\n\\nBeware! The Aby can be addictive. Once you\\u2019ve had one, you may find that no other cat will do.\",\n" +
                "    \"round_img_url\": \"https://cattime.com/assets/uploads/2011/12/file_2678_Abyssinian-cat-breed.jpg\",\n" +
                "    \"short_description\": \"A love of heights is a signal trait of the Abyssinian. He likes to be as high up as possible and will appreciate having one or more ceiling-height cat trees.\",\n" +
                "    \"size\": \"This is a medium-size cat weighing 6 to 10 pounds.\",\n" +
                "    \"vital_stats\": {\n" +
                "      \"Length\": \"12 to 16 inches\",\n" +
                "      \"Life Span\": \"9 to 15 years\",\n" +
                "      \"Origin\": \"Southeast Asia\",\n" +
                "      \"Weight\": \"6 to 10 pounds\"\n" +
                "    }\n" +
                "  }" +
                "]");
    }
}